#!/usr/bin/env python3

import socket
import threading
import struct as st
import pandas as pd
import datetime

HOST = ''
PORT = 6969
df = pd.read_csv("/Users/davidmullings/Desktop/College/junior_first_semester/ufa/dues_tracker/Paid Members 2021-2022 (cleaned) - updated_dues (1).csv")
df["Name"] = df["Name"].astype('string')
df["EID"] = df["EID"].astype('string')

meeting_title: str = datetime.datetime.now().strftime('%m_%d_%Y')
attendance: str = []
for i in range(0, len(df.index)):
    attendance.append('Absent')
df[meeting_title] = attendance
e: threading.Event = threading.Event()

def quit_on_stdin(event: threading.Event):
    user_input: str = '\n'
    while not event.is_set():

        try:
            user_input = input()
            if user_input == 'q':
                event.set()

                break
        except EOFError:
            event.set()
            break

def unpack_message(data: bytes) -> tuple:
    format: str = '<?50s'
    action, message = st.unpack(format, data)
    return action, message.decode('utf-8')

def pack_message(field: bool, found: bool, dues: bool) -> bytes:
    format: str = '<???'
    p = st.pack(format, field, found, dues)
    return p

def dataframe_perform_actions(action: chr, message: str, last_eid: str, dataframe_lock: threading.Lock) -> tuple:
    if action == 0:
        dataframe_lock.acquire()
        eid_entry = df.loc[df["EID"] == message]
        dataframe_lock.release()
        if len(eid_entry) > 0:
            dataframe_lock.acquire()
            df.loc[df['EID'] == message, [meeting_title]] = 'Present'
            dataframe_lock.release()
            return 0, 1, eid_entry.iloc[0]["Dues Paid"] >= 30
        else:
            return 0, 0, 0
    elif action == 1:
        dataframe_lock.acquire()
        name_entry = df.loc[df["Name"] == message]
        dataframe_lock.release()
        if len(name_entry) > 0:
            dataframe_lock.acquire()
            df.loc[df["Name"] == message + '', ['EID']] = str(last_eid)
            dataframe_lock.release()
        else:
            return 1, 0, 0
        dataframe_lock.acquire()
        df.loc[df['Name'] == message, [meeting_title]] = 'Present'
        dataframe_lock.release()
        return 1, 1, name_entry.iloc[0]["Dues Paid"] >= 30



def interact(conn: socket.socket, addr: socket.AddressInfo, dataframe_lock: threading.Lock):
    with conn:
        print('Connected by', addr)
        last_eid: str = ''
        while not e.is_set():
            data: bytes = conn.recv(64)
            if not data: break

            # unpack message and perform actions
            action, message = unpack_message(data)
            message = message.rstrip('\x00')
            if (action == 0):
                last_eid = message

            # search / write to Pandas dataframe
            field, found, dues = dataframe_perform_actions(action, message, last_eid, dataframe_lock)
            conn.sendall(pack_message(field, found, dues))
    
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind((HOST, PORT))
    t1 = threading.Thread(target=quit_on_stdin, args=(e,))
    t1.start()
    s.listen(6)
    dataframe_lock: threading.Lock = threading.Lock()
    while not e.is_set():
        conn, addr = s.accept()
        temp = threading.Thread(target=interact, args=(conn, addr, dataframe_lock))
        temp.start()

df.to_csv('/Users/davidmullings/Desktop/College/junior_first_semester/ufa/dues_tracker/updated_dues.csv')


        